-- =============================================================================================
-- V1 - core schema for the distributed payments platform.
--
-- Read this file top to bottom before writing any Java: it is the data model the whole project
-- argues about. Every table has a one-paragraph justification, because in an interview you will be
-- asked why a column exists, not what its type is.
--
-- Conventions used throughout:
--   * Money is (amount_minor BIGINT, currency CHAR(3)). 12500 + 'INR' is Rs. 125.00. There is no
--     NUMERIC and there is definitely no DOUBLE PRECISION: minor units are exact, they match the
--     wire format, and they make "amounts are integers" impossible to violate by accident.
--   * Timestamps are TIMESTAMPTZ and always stored in UTC. A payment system that stores local time
--     loses money twice a year.
--   * Primary keys are UUIDs generated by the application, not by the database. The application
--     needs the id before the INSERT (to build the outbox event and the response), and an
--     application-generated id keeps the write path to a single round trip.
--   * Flyway owns this schema. Hibernate runs with ddl-auto=validate and never alters it.
-- =============================================================================================

-- ---------------------------------------------------------------------------------------------
-- payments - the aggregate root. One row per payment, mutated only through the state machine.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE payments (
    id                    UUID         PRIMARY KEY,
    merchant_id           VARCHAR(64)  NOT NULL,
    amount_minor          BIGINT       NOT NULL,
    currency              CHAR(3)      NOT NULL,
    status                VARCHAR(32)  NOT NULL,
    payment_method_token  VARCHAR(128) NOT NULL,
    -- The merchant's own reference for this payment (an order number, typically). Never a primary
    -- key: callers do not get to choose our identifiers, and two merchants may legitimately use
    -- the same reference.
    external_reference    VARCHAR(128),
    -- Optimistic locking. Hibernate appends "AND version = ?" to every UPDATE; when two concurrent
    -- captures race, the second one updates zero rows and fails instead of double-recording.
    version               BIGINT       NOT NULL DEFAULT 0,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- Amounts are positive; a negative payment is a refund and lives in its own table.
    CONSTRAINT payments_amount_positive CHECK (amount_minor > 0),
    CONSTRAINT payments_currency_format CHECK (currency ~ '^[A-Z]{3}$'),
    -- The state machine also lives in Java. Duplicating the enum here is deliberate: the database
    -- is the last line of defence, and it survives a buggy deploy that the application does not.
    CONSTRAINT payments_status_known CHECK (status IN (
        'CREATED', 'PROCESSING', 'AUTHORIZED', 'CAPTURED', 'FAILED', 'REFUND_PENDING', 'REFUNDED'))
);

-- Indexes below are the ones the API's own queries need on day one. Do not add speculative
-- indexes: every index is a write cost, and Phase 8 will tell you which ones the load test
-- actually wants. Justify each addition in docs/performance/ with a measured before/after.
CREATE INDEX idx_payments_merchant_created ON payments (merchant_id, created_at DESC);
CREATE INDEX idx_payments_status ON payments (status) WHERE status IN ('CREATED', 'PROCESSING', 'REFUND_PENDING');
COMMENT ON INDEX idx_payments_status IS
    'Partial index: only in-flight payments are ever scanned by status. A full index on status
     would be mostly CAPTURED rows that nothing queries by status alone.';

-- ---------------------------------------------------------------------------------------------
-- payment_attempts - one row per call to the external processor.
--
-- This table is why "did we already charge this card?" is answerable after a timeout. When the
-- processor times out, the payment row still says PROCESSING and you do not know whether the money
-- moved; the attempt row records what you sent, when, and what came back (or that nothing did).
-- It is also the raw material for the retry/circuit-breaker discussion in Phase 3.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE payment_attempts (
    id                  UUID         PRIMARY KEY,
    payment_id          UUID         NOT NULL REFERENCES payments (id),
    attempt_number      INT          NOT NULL,
    -- AUTHORIZE | CAPTURE | REFUND - which processor operation this attempt performed.
    operation           VARCHAR(16)  NOT NULL,
    -- PENDING | SUCCESS | FAILURE | TIMEOUT | UNKNOWN. UNKNOWN is not laziness: a timed-out call
    -- whose outcome was never confirmed genuinely is unknown, and pretending otherwise is how
    -- double charges happen.
    outcome             VARCHAR(16)  NOT NULL,
    processor_reference VARCHAR(128),
    error_code          VARCHAR(64),
    latency_ms          INT,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT payment_attempts_unique_attempt UNIQUE (payment_id, operation, attempt_number),
    CONSTRAINT payment_attempts_outcome_known CHECK (outcome IN
        ('PENDING', 'SUCCESS', 'FAILURE', 'TIMEOUT', 'UNKNOWN'))
);

CREATE INDEX idx_payment_attempts_payment ON payment_attempts (payment_id, created_at);

-- ---------------------------------------------------------------------------------------------
-- refunds - a refund is its own entity, not a flag on the payment.
--
-- It has its own lifecycle, its own idempotency key and its own failure mode; modelling it as
-- payments.refunded = true makes "the refund failed, try again" unrepresentable. Full refunds only
-- in this project - partial refunds are listed under Known Limitations in the README, which is a
-- better answer than a half-built implementation.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE refunds (
    id           UUID        PRIMARY KEY,
    payment_id   UUID        NOT NULL REFERENCES payments (id),
    amount_minor BIGINT      NOT NULL,
    currency     CHAR(3)     NOT NULL,
    status       VARCHAR(32) NOT NULL,
    reason       VARCHAR(256),
    version      BIGINT      NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT refunds_amount_positive CHECK (amount_minor > 0),
    CONSTRAINT refunds_status_known CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED'))
);

-- One outstanding refund per payment. Full refunds only, so a second successful refund would be a
-- double reversal. The partial index lets a FAILED refund be retried with a new row.
CREATE UNIQUE INDEX uq_refunds_one_active_per_payment
    ON refunds (payment_id) WHERE status IN ('PENDING', 'SUCCEEDED');

-- ---------------------------------------------------------------------------------------------
-- idempotency_keys - the flagship table.
--
-- The contract: a client that retries POST /payments with the same Idempotency-Key gets the same
-- payment back, and no second charge. Three columns carry that contract:
--
--   idempotency_key  the client's key, scoped per merchant - two merchants may both send
--                    "order-1" and they are different payments.
--   request_hash     a hash of the canonical request body. Same key + DIFFERENT payload must be
--                    an error (422), never a silent replay of the first payment; that combination
--                    means the client has a bug, and hiding it would charge the wrong amount.
--   payment_id       what to return on replay.
--
-- The UNIQUE constraint is the whole point. Redis can serve the lookup faster (Phase 5), but under
-- true concurrency two application instances can both miss the cache; the database constraint is
-- the only thing that makes "exactly one payment" a fact rather than a hope. Insert this row in
-- the SAME transaction as the payment, and let the duplicate-key violation be your happy path.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE idempotency_keys (
    id               UUID         PRIMARY KEY,
    merchant_id      VARCHAR(64)  NOT NULL,
    idempotency_key  VARCHAR(128) NOT NULL,
    request_hash     CHAR(64)     NOT NULL,           -- SHA-256 hex of the canonical request
    payment_id       UUID         REFERENCES payments (id),
    response_status  INT,
    response_body    JSONB,                           -- replayed verbatim, so the retry is byte-identical
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- Keys are not kept forever. Expiry is a business decision (24h here) and a housekeeping job
    -- deletes expired rows; unbounded growth on the hottest write table is a real outage.
    expires_at       TIMESTAMPTZ  NOT NULL,

    CONSTRAINT uq_idempotency_key_per_merchant UNIQUE (merchant_id, idempotency_key)
);

CREATE INDEX idx_idempotency_keys_expiry ON idempotency_keys (expires_at);

-- ---------------------------------------------------------------------------------------------
-- outbox_events - the transactional outbox (Phase 4).
--
-- The problem it solves: "UPDATE payment; COMMIT; kafka.send()" can commit the state change and
-- then fail to publish, leaving the database saying AUTHORIZED while no downstream service ever
-- hears about it. Writing the event into THIS table inside the same transaction as the state
-- change makes the two atomic - one commit, both facts or neither.
--
-- A separate publisher then polls unpublished rows, sends them to Kafka, and marks them published.
-- Because publish-then-mark is not atomic, the same event can be published twice after a crash:
-- that is why this design is at-least-once delivery, and why consumers must be idempotent
-- (see processed_events). Never call this exactly-once.
--
-- The polling publisher's query is deliberately boring:
--   SELECT * FROM outbox_events WHERE published_at IS NULL
--   ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 100;
-- SKIP LOCKED is what lets several instances drain the outbox concurrently without fighting.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE outbox_events (
    id             UUID         PRIMARY KEY,
    -- aggregate_id becomes the Kafka partition key, so all events for one payment land in one
    -- partition and stay ordered relative to each other. Ordering ACROSS payments is not
    -- guaranteed and nothing should depend on it.
    aggregate_type VARCHAR(32)  NOT NULL,             -- 'PAYMENT' | 'REFUND'
    aggregate_id   UUID         NOT NULL,
    event_type     VARCHAR(64)  NOT NULL,             -- 'payment.authorized', 'payment.captured', ...
    payload        JSONB        NOT NULL,
    -- Set once the broker has acknowledged. NULL means "not published yet", which is the only
    -- state the publisher queries.
    published_at   TIMESTAMPTZ,
    attempts       INT          NOT NULL DEFAULT 0,
    last_error     VARCHAR(512),
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Partial index: the publisher only ever reads unpublished rows, and this keeps the index small
-- even after the table has millions of published rows in it.
CREATE INDEX idx_outbox_unpublished ON outbox_events (created_at) WHERE published_at IS NULL;

-- =============================================================================================
-- OWNERSHIP BOUNDARY
--
-- Everything above is owned by payment-service. The two tables below are owned by ledger-service.
-- They are drafted here so the whole data model is visible in one place while you design Phase 1,
-- and because both services share one PostgreSQL instance in local development.
--
-- TODO Phase 4 (Day 25): move these two tables into ledger-service's own Flyway migration and its
-- own schema (CREATE SCHEMA ledger), and delete them from this file with a V2 migration. Two
-- services writing the same table is not a distributed system, it is a shared database with extra
-- steps - and an interviewer will ask. Doing the move yourself, and being able to explain why, is
-- worth more than getting the boundary right by luck on day one.
-- =============================================================================================

-- ---------------------------------------------------------------------------------------------
-- processed_events - how a consumer stays idempotent (Phase 4, owned by ledger-service).
--
-- Kafka gives you at-least-once delivery: after a rebalance or a crash between processing and
-- offset commit, the same event arrives again. The consumer records the event id here inside the
-- SAME transaction that writes the ledger entries, so the second delivery hits this primary key,
-- rolls back, and posts nothing. At-least-once transport plus this table equals exactly-once
-- BUSINESS EFFECTS - which is the only kind of exactly-once anyone can honestly claim.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE processed_events (
    event_id     UUID        PRIMARY KEY,             -- the outbox_events.id, carried in the message
    consumer     VARCHAR(64) NOT NULL,                -- which consumer group processed it
    processed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------------------------
-- ledger_entries - double-entry, append-only (Phase 4, owned by ledger-service).
--
-- Every money movement is at least two rows: one debit and one credit, with equal magnitude, in
-- the same transaction, sharing a transaction_ref. For a capture:
--     DEBIT  customer_receivable   12500 INR
--     CREDIT merchant_payable      12500 INR
-- and a refund posts the mirror image. The invariant the tests assert is simply
--     SUM(amount_minor) FILTER (WHERE direction='DEBIT')
--   = SUM(amount_minor) FILTER (WHERE direction='CREDIT')
-- for every transaction_ref, and globally.
--
-- Append-only means exactly that: corrections are new reversing entries, never UPDATE or DELETE.
-- An audit trail you can edit is not an audit trail. Enforce it in Phase 4 by granting the
-- application role only INSERT and SELECT on this table - a comment is a wish, a GRANT is a rule.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE ledger_entries (
    id              UUID         PRIMARY KEY,
    -- Groups the two (or more) sides of one movement. The balance invariant is checked per ref.
    transaction_ref UUID         NOT NULL,
    payment_id      UUID         NOT NULL,
    -- Chart of accounts, kept deliberately tiny: CUSTOMER_RECEIVABLE, MERCHANT_PAYABLE,
    -- PLATFORM_FEE. Three accounts are enough to demonstrate double entry; thirty would be a
    -- different project.
    account         VARCHAR(64)  NOT NULL,
    direction       VARCHAR(6)   NOT NULL,
    amount_minor    BIGINT       NOT NULL,
    currency        CHAR(3)      NOT NULL,
    -- The event that produced this line, for tracing a ledger row back to its cause.
    event_id        UUID         NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ledger_direction_known CHECK (direction IN ('DEBIT', 'CREDIT')),
    -- Amounts are always positive; the sign lives in `direction`. Allowing negative amounts means
    -- there are two ways to express the same movement, and two ways to express one thing is one
    -- way too many in a ledger.
    CONSTRAINT ledger_amount_positive CHECK (amount_minor > 0)
);

CREATE INDEX idx_ledger_payment ON ledger_entries (payment_id);
CREATE INDEX idx_ledger_transaction ON ledger_entries (transaction_ref);
CREATE UNIQUE INDEX uq_ledger_event_account_direction
    ON ledger_entries (event_id, account, direction);
COMMENT ON INDEX uq_ledger_event_account_direction IS
    'Belt and braces with processed_events: even if the idempotency check is bypassed, one event
     cannot post the same account/direction line twice.';
